services:
  - type: web
    name: n8n
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: samwowv
      - key: N8N_BASIC_AUTH_PASSWORD
        value: samwowv
      - key: N8N_PORT
        value: "5678"
      - key: N8N_HOST
        value: 0.0.0.0
      - key: WEBHOOK_URL
        value: https://n8n-render-8lfd.onrender.com